# gitops/app-of-apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps-infra
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/samuelamaralls/gitops
        revision: main
        files:
          - path: apps.yaml   # aqui vai apenas o apps.yaml
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          valueFiles:
            - 'infra/{{name}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
