auth:
  adminUser: admin
  adminPassword: admin
postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: "12345678"
    database: keycloakdb

  persistence:
    enabled: true              
    size: 8Gi 